name: "AWS VPC Build"

on:
  push:
    branches: ["main"]
    paths:
      - 'terraform/**'
      - '.github/workflows/tf-create.yml'
  pull_request:
    branches: ["main"]
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  terraform:
    uses: rdavis542/aws-github-workflows/.github/workflows/tf-plan-apply.yml@main
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    with:
      aws_region: us-east-2
      tf_vars: '{"region":"us-east-2","cidr_block":"10.0.0.0/16","subnet_public_a":"10.0.0.0/19","subnet_public_b":"10.0.64.0/19","subnet_public_c":"10.0.128.0/19","subnet_private_a":"10.0.32.0/19","subnet_private_b":"10.0.96.0/19","subnet_private_c":"10.0.160.0/19","enable_nat_gateway":"false"}'
    secrets: inherit
